# Config file for automatic testing at travis-ci.org

sudo: required

language: python

python:
  - "3.6"

install:
  - sudo apt-get update -y
  - make install

script:
  - make test
  - codeclimate-test-reporter --file .coverage
